name: Compress assets
on: push

jobs:
  compress:
    name: Brotli
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Compress assets
        uses: Timmy/brotli-action@v1
        with:
          args: '-Z *.html *.css *.js'
      - name: Upload assets
        uses: actions/upload-artifact@v1
        with:
          name: assets
          path: .
